require("logger")
logger.Category("battle", "WARN")
logger.Category("cocos2d", "WARN")
logger.Category("drama", "WARN")
logger.Category("login", "WARN")
logger.Category("guide", "WARN")
logger.Category("msg", "WARN")
logger.Category("system", "WARN")
logger.Category("misc", "WARN")
logger.Category("temp", "WARN")
