local Base = require("BattleShow.Action.Base")
local Define = require("BattleShow.BattleDefine")
module((...), package.seeall)
class = Base.class:subclass()
function class:initialize(...)
  super.initialize(self, ...)
end
function class:PlayAction()
  local srcPos = ccp(self.owner:getPosition())
  local stageAni1 = self:RunHero(self.owner, self.info.stage1)
  stageAni1:RunAnimation()
  local stageAni2 = self:RunEffect(self.owner, self.info.stage2)
  stageAni2:RunAnimationAutoRemove(self.sync:Join())
  self.sync:Sync()
  self.owner:runAction(self:RepeatAction(CCRotateBy:create(0.3, 180)))
  local hitFunc = bind(self.HitTarget, self)
  self:ForeachTarget(hitFunc, nil, "HIT")
  self.owner:stopAllActions()
  self.owner:setRotation(0)
  self.owner:setPosition(srcPos)
  local passFunc = bind(self.PassiveTarget, self)
  self:ForeachTarget(passFunc, nil, "PASSIVE")
  local buffFunc = bind(self.BuffTarget, self)
  self:ForeachTarget(buffFunc, nil, "BUFF")
end
function class:HitTarget(target, hp, status, shield, info)
  local srcPos = ccp(self.owner:getPosition())
  local dstPos = ccp(target:getPosition())
  self:RunMoveTo(srcPos, dstPos)
  self:RunPassiveAndBuff(target, hp, status, shield, info)
  local stageAni3 = self:RunHero(target, self.info.stage3, true)
  local stageAni4 = self:RunEffect(target, self.info.stage4, hp == 0)
  local heroWaitSign = self:CheckHeroNextEffect(target, self.sync)
  stageAni3:RunAnimationByWaitSign(nil, function()
    stageAni3:RemoveAnimation()
    target:CheckDead()
    heroWaitSign()
  end, Define.ANI_TIMEOUT)
  stageAni4:RunAnimationAutoRemove()
end
function class:RunMoveTo(srcPos, dstPos)
  local moveOffset = 1000
  if not (dstPos.y > srcPos.y) or not moveOffset then
    moveOffset = -moveOffset
  end
  local waitSign = self.sync:Join()
  local move = CCMoveTo:create(1, ccp(dstPos.x, dstPos.y + moveOffset))
  local squence = Logic:Get("AniMgr"):CreateSequence({move, waitSign})
  self.owner:runAction(squence)
  self.sync:Sync()
end
