local Base = require("BattleShow.Action.Base")
local Define = require("BattleShow.BattleDefine")
module((...), package.seeall)
class = Base.class:subclass()
function class:initialize(...)
  super.initialize(self, ...)
end
function class:PlayAction()
  local stageAni1 = self:RunHero(self.owner, self.info.stage1)
  stageAni1:RunAnimationAutoRemove(self.sync:Join())
  local stageAni2 = self:RunEffect(self.owner, self.info.stage2)
  stageAni2:RunAnimationAutoRemove(self.sync:Join())
  self:DelayTime(self.info.param)
  self.hasHit = false
  local hitFunc = bind(self.HitTarget, self)
  self:ForeachTarget(hitFunc, nil, "HIT")
  self.sync:Sync()
  self:RunFeedBackEffect(self.info.feedback, self.hasHit, self.sync)
  self.sync:Sync()
  local passFunc = bind(self.PassiveTarget, self)
  self:ForeachTarget(passFunc, nil, "PASSIVE")
  local buffFunc = bind(self.BuffTarget, self)
  self:ForeachTarget(buffFunc, nil, "BUFF")
end
function class:HitTarget(target, hp, status, shield, info)
  self.hasHit = self.hasHit or hp ~= 0 or shield ~= 0
  self:RunPassiveAndBuff(target, hp, status, shield, info)
  local stageAni4 = self:RunEffect(target, self.info.stage4, hp == 0)
  stageAni4:RunAnimationAutoRemove()
  self:DelayTime(self.info.param)
  local stageAni3 = self:RunHero(target, self.info.stage3)
  local heroWaitSign = self.sync:Join()
  stageAni3:RunAnimationByWaitSign(nil, function()
    stageAni3:RemoveAnimation()
    target:CheckShieldRemove()
    target:CheckDead()
    heroWaitSign()
  end, Define.ANI_TIMEOUT)
end
