local Base = require("BattleShow.Action.Base")
local Define = require("BattleShow.BattleDefine")
module((...), package.seeall)
class = Base.class:subclass()
function class:initialize(...)
  super.initialize(self, ...)
end
function class:PlayAction()
  local srcPos = ccp(self.owner:getPosition())
  local stageAni1 = self:RunHero(self.owner, self.info.stage1)
  stageAni1:RunAnimationAutoRemove()
  local stageAni2 = self:RunEffectFolow(self.owner, self.info.stage2)
  stageAni2:RunAnimationAutoRemove()
  local hitFunc = bind(self.HitTarget, self)
  self:ForeachTarget(hitFunc, nil, "HIT")
  Logic:Get("AniMgr"):MoveToAndRotateSync(self.owner, 0.1, srcPos, 0)
  local passFunc = bind(self.PassiveTarget, self)
  self:ForeachTarget(passFunc, nil, "PASSIVE")
  local buffFunc = bind(self.BuffTarget, self)
  self:ForeachTarget(buffFunc, nil, "BUFF")
end
function class:HitTarget(target, hp, status, shield, info)
  self:RunHeroActions(self.owner, target)
  self:RunTargetHitted(target, hp, status, shield, info)
end
function class:RunHeroActions(owner, target)
  local time, angle, dstPos = self:GetUnitAngleInfo(owner, target, self.info, 0.75, self:GetOffsetY())
  local move = CCEaseBackOut:create(CCMoveTo:create(0.7, dstPos))
  local waitSign = self.sync:Join()
  local sequence = Logic:Get("AniMgr"):CreateSequence({move, waitSign})
  local rotate = CCRotateTo:create(0.2, angle)
  local spawn = Logic:Get("AniMgr"):CreateSpawn({rotate, sequence})
  owner:runAction(spawn)
  self.sync:Sync()
end
function class:RunTargetHitted(target, hp, status, shield, info, angle, waitSign)
  self:RunPassiveAndBuff(target, hp, status, shield, info)
  local stageAni3 = self:RunHero(target, self.info.stage3, true)
  local stageAni4 = self:RunEffect(target, self.info.stage4, hp == 0, true)
  if stageAni4 and stageAni4:GetChild("rootNode") and angle then
    stageAni4:GetChild("rootNode"):setRotation(2 / math.pi + angle)
  end
  local heroWaitSign = self:CheckHeroNextEffect(target, self.sync)
  stageAni3:RunAnimationByWaitSign(nil, function()
    stageAni3:RemoveAnimation()
    target:CheckDead(angle)
    heroWaitSign()
    waitSign = waitSign and waitSign()
  end, Define.ANI_TIMEOUT)
  stageAni4:RunAnimationAutoRemove()
end
