local Base = require("BattleShow.Action.Base")
local Define = require("BattleShow.BattleDefine")
module((...), package.seeall)
class = Base.class:subclass()
function class:initialize(...)
  super.initialize(self, ...)
end
function class:PlayAction()
  local heroOrginPosX, heroOrginPosY = self.owner:getPosition()
  self.actTime = 0.3
  local hitFunc = bind(self.HitTarget, self)
  self:ForeachTarget(hitFunc, nil, "HIT")
  Logic:Get("AniMgr"):MoveToSync(self.owner, self.actTime, ccp(heroOrginPosX, heroOrginPosY))
  local passFunc = bind(self.PassiveTarget, self)
  self:ForeachTarget(passFunc, nil, "PASSIVE")
  local buffFunc = bind(self.BuffTarget, self)
  self:ForeachTarget(buffFunc, nil, "BUFF")
end
function class:HitTarget(target, hp, status, shield, info)
  local tx, ty = target:getPosition()
  local cz = target:getContentSize()
  local scale = target:getScale()
  local offsetY = target:IsEnemy() and -cz.height * scale or cz.height * scale
  self.actTime = self:GetMovingTimeByUnits(self.owner, target, {param = 1.1})
  Logic:Get("AniMgr"):AccMoveToSync(self.owner, self.actTime, ccp(tx, ty + offsetY), true)
  local stageAni1 = self:RunHero(self.owner, self.info.stage1)
  stageAni1:RunAnimationByWaitSign(nil, self.sync:Join())
  local stageAni4 = self:RunEffect(target, self.info.stage4, hp == 0, true)
  stageAni4:RunAnimationAutoRemove(self.sync:Join())
  self:DelayTime(self.info.param)
  self:RunPassiveAndBuff(target, hp, status, shield, info)
  local stageAni3 = self:RunHero(target, self.info.stage3, true)
  local heroWaitSign = self.sync:Join()
  stageAni3:RunAnimationByWaitSign(nil, function()
    stageAni3:RemoveAnimation()
    target:CheckDead()
    heroWaitSign()
  end, Define.ANI_TIMEOUT)
  self.sync:Sync()
end
