local Base = require("BattleShow.Action.Base")
local Define = require("BattleShow.BattleDefine")
module((...), package.seeall)
class = Base.class:subclass()
function class:initialize(...)
  super.initialize(self, ...)
end
function class:PlayAction()
  local srcPos = ccp(self.owner:getPosition())
  self.dstPos = srcPos
  local stageAni1 = self:RunHero(self.owner, self.info.stage1)
  stageAni1:RunAnimation()
  local stageAni2 = self:RunEffect(self.owner, self.info.stage2)
  stageAni2:RunAnimationAutoRemove(self.sync:Join())
  self.sync:Sync()
  self.owner:runAction(self:RepeatAction(CCRotateBy:create(0.3, 180)))
  local hitFunc = bind(self.HitTarget, self)
  self:ForeachTarget(hitFunc, nil, "HIT")
  self:RunBezier(self.dstPos, srcPos)
  local passFunc = bind(self.PassiveTarget, self)
  self:ForeachTarget(passFunc, nil, "PASSIVE")
  local buffFunc = bind(self.BuffTarget, self)
  self:ForeachTarget(buffFunc, nil, "BUFF")
  stageAni1:RemoveAnimation()
  self.owner:stopAllActions()
  self.owner:setRotation(0)
end
function class:HitTarget(target, hp, status, shield, info)
  local srcPos = ccp(self.owner:getPosition())
  local dstPos = ccp(target:getPosition())
  self:RunBezier(srcPos, dstPos)
  self.dstPos = dstPos
  self:RunPassiveAndBuff(target, hp, status, shield, info)
  local stageAni3 = self:RunHero(target, self.info.stage3, true)
  local stageAni4 = self:RunEffect(target, self.info.stage4, hp == 0)
  local heroWaitSign = self:CheckHeroNextEffect(target, self.sync)
  stageAni3:RunAnimationByWaitSign(nil, function()
    stageAni3:RemoveAnimation()
    target:CheckDead()
    heroWaitSign()
  end, Define.ANI_TIMEOUT)
  stageAni4:RunAnimationAutoRemove()
end
function class:RunBezier(srcPos, dstPos)
  local waitSign = self.sync:Join()
  local curveAction = self:GetBezierAction(srcPos, dstPos, 0.5, 100)
  local squence = Logic:Get("AniMgr"):CreateSequence({curveAction, waitSign})
  self.owner:runAction(squence)
  self.sync:Sync()
end
